# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  "'plugin-Comment.nvim'" = {
    pname = "'plugin-Comment.nvim'";
    version = "5f01c1a89adafc52bf34e3bf690f80d9d726715d";
    src = fetchFromGitHub ({
      owner = "numToStr";
      repo = "Comment.nvim";
      rev = "5f01c1a89adafc52bf34e3bf690f80d9d726715d";
      fetchSubmodules = false;
      sha256 = "sha256-po1MyuuOH3e8yJTAtkxnusFSJuNpQnjpe+zfWPoO62E=";
    });
    date = "2022-11-18";
  };
  "'plugin-LuaSnip'" = {
    pname = "'plugin-LuaSnip'";
    version = "59bb7ea0d26524cef0fce6dcf6192963ec232fdf";
    src = fetchFromGitHub ({
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "59bb7ea0d26524cef0fce6dcf6192963ec232fdf";
      fetchSubmodules = false;
      sha256 = "sha256-TlkRZolP6IKJ5ESuw5duX1+3sXEFPVg4mqmfYNH6m/w=";
    });
    date = "2022-11-17";
  };
  "'plugin-SchemaStore.nvim'" = {
    pname = "'plugin-SchemaStore.nvim'";
    version = "f92c7fce6a8ddb5b5b906d5cf7a2985b4741b9a8";
    src = fetchFromGitHub ({
      owner = "b0o";
      repo = "SchemaStore.nvim";
      rev = "f92c7fce6a8ddb5b5b906d5cf7a2985b4741b9a8";
      fetchSubmodules = false;
      sha256 = "sha256-wzzTco8Tkn+gsOho8cq/KZTUiQiHiICn7v8XpLr6Uh8=";
    });
    date = "2022-11-10";
  };
  "'plugin-bufdelete.nvim'" = {
    pname = "'plugin-bufdelete.nvim'";
    version = "3ebf4a98c380ec27b3066eaa5f1fdda332df1a9d";
    src = fetchFromGitHub ({
      owner = "famiu";
      repo = "bufdelete.nvim";
      rev = "3ebf4a98c380ec27b3066eaa5f1fdda332df1a9d";
      fetchSubmodules = false;
      sha256 = "sha256-+yE/7gj5QDm4vxEISC5Nq+1JdrKebEFP2UfYOA+F1LI=";
    });
    date = "2022-11-16";
  };
  "'plugin-cmp-cmdline'" = {
    pname = "'plugin-cmp-cmdline'";
    version = "8bc9c4a34b223888b7ffbe45c4fe39a7bee5b74d";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-cmdline";
      rev = "8bc9c4a34b223888b7ffbe45c4fe39a7bee5b74d";
      fetchSubmodules = false;
      sha256 = "sha256-+CMZXzRNaA6X1rBECmCbQTOTl4dV89Anf9m1cBWzqGc=";
    });
    date = "2022-11-13";
  };
  "'plugin-cmp-git'" = {
    pname = "'plugin-cmp-git'";
    version = "169202582f900b0e189eed5153b291383bfbba47";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-git";
      rev = "169202582f900b0e189eed5153b291383bfbba47";
      fetchSubmodules = false;
      sha256 = "sha256-1UjjqMBq3+B/TKVdYH4N3a0MZLs4LKoLsdAF0gyP0TY=";
    });
    date = "2021-10-29";
  };
  "'plugin-cmp-nvim-lsp'" = {
    pname = "'plugin-cmp-nvim-lsp'";
    version = "59224771f91b86d1de12570b4070fe4ad7cd1eeb";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-nvim-lsp";
      rev = "59224771f91b86d1de12570b4070fe4ad7cd1eeb";
      fetchSubmodules = false;
      sha256 = "sha256-Mqkp8IH/laUx0cK7S0BjusTT+OtOOJOamZM4+93RHdU=";
    });
    date = "2022-11-16";
  };
  "'plugin-cmp-path'" = {
    pname = "'plugin-cmp-path'";
    version = "91ff86cd9c29299a64f968ebb45846c485725f23";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-path";
      rev = "91ff86cd9c29299a64f968ebb45846c485725f23";
      fetchSubmodules = false;
      sha256 = "sha256-thppiiV3wjIaZnAXmsh7j3DUc6ceSCvGzviwFUnoPaI=";
    });
    date = "2022-10-03";
  };
  "'plugin-cmp_luasnip'" = {
    pname = "'plugin-cmp_luasnip'";
    version = "18095520391186d634a0045dacaa346291096566";
    src = fetchFromGitHub ({
      owner = "saadparwaiz1";
      repo = "cmp_luasnip";
      rev = "18095520391186d634a0045dacaa346291096566";
      fetchSubmodules = false;
      sha256 = "sha256-Z5SPy3j2oHFxJ7bK8DP8Q/oRyLEMlnWyIfDaQcNVIS0=";
    });
    date = "2022-10-28";
  };
  "'plugin-colorful-winsep.nvim'" = {
    pname = "'plugin-colorful-winsep.nvim'";
    version = "9a474934a27203d1c2e9943c94a29165dd81823d";
    src = fetchFromGitHub ({
      owner = "nvim-zh";
      repo = "colorful-winsep.nvim";
      rev = "9a474934a27203d1c2e9943c94a29165dd81823d";
      fetchSubmodules = false;
      sha256 = "sha256-vXLy1Q0UAm3dBWAkqNjfejrhVsNlO4sZabj8kga/8Fg=";
    });
    date = "2022-11-13";
  };
  "'plugin-diffview.nvim'" = {
    pname = "'plugin-diffview.nvim'";
    version = "f32a7224096cca11c3c91b0dd412808e63f3d720";
    src = fetchFromGitHub ({
      owner = "sindrets";
      repo = "diffview.nvim";
      rev = "f32a7224096cca11c3c91b0dd412808e63f3d720";
      fetchSubmodules = false;
      sha256 = "sha256-aDweuvwkF8kb+lFUuBxgPeNfhX9wnm93LcBea7HkrSg=";
    });
    date = "2022-11-17";
  };
  "'plugin-dressing.nvim'" = {
    pname = "'plugin-dressing.nvim'";
    version = "7894d5bc504deacf37f0a479a53fa4746fe30a45";
    src = fetchFromGitHub ({
      owner = "stevearc";
      repo = "dressing.nvim";
      rev = "7894d5bc504deacf37f0a479a53fa4746fe30a45";
      fetchSubmodules = false;
      sha256 = "sha256-gR+cvJztRhkQ+vGhZ1JYgyEZA2TjNaJ1aGkeTA3yiMs=";
    });
    date = "2022-11-18";
  };
  "'plugin-editorconfig.nvim'" = {
    pname = "'plugin-editorconfig.nvim'";
    version = "2af880947129f1ab776b732a4eecb92528472ef5";
    src = fetchFromGitHub ({
      owner = "gpanders";
      repo = "editorconfig.nvim";
      rev = "2af880947129f1ab776b732a4eecb92528472ef5";
      fetchSubmodules = false;
      sha256 = "sha256-PM6GEUJMJTFD5AAS+hZy+l//tCPLeezxIcAZiooBZ+c=";
    });
    date = "2022-11-18";
  };
  "'plugin-fm-nvim'" = {
    pname = "'plugin-fm-nvim'";
    version = "8e6a77049330e7c797eb9e63affd75eb796fe75e";
    src = fetchFromGitHub ({
      owner = "is0n";
      repo = "fm-nvim";
      rev = "8e6a77049330e7c797eb9e63affd75eb796fe75e";
      fetchSubmodules = false;
      sha256 = "sha256-I29p08P4Wh/LLTDZIQ2TkYy5Kdj0G8loU6k3eFM+iVE=";
    });
    date = "2022-10-10";
  };
  "'plugin-git-worktree.nvim'" = {
    pname = "'plugin-git-worktree.nvim'";
    version = "d7f4e2584e81670154f07ca9fa5dd791d9c1b458";
    src = fetchFromGitHub ({
      owner = "ThePrimeagen";
      repo = "git-worktree.nvim";
      rev = "d7f4e2584e81670154f07ca9fa5dd791d9c1b458";
      fetchSubmodules = false;
      sha256 = "sha256-pkJkdt2XC1w0s1VpnxJFnoYiEgD01MZ7a5i2AlU1hMw=";
    });
    date = "2021-12-24";
  };
  "'plugin-gitlinker.nvim'" = {
    pname = "'plugin-gitlinker.nvim'";
    version = "c68d4873a14d2ae614875685ccca2e49472989e8";
    src = fetchFromGitHub ({
      owner = "ruifm";
      repo = "gitlinker.nvim";
      rev = "c68d4873a14d2ae614875685ccca2e49472989e8";
      fetchSubmodules = false;
      sha256 = "sha256-yPEKz2iahD1dwXCXeci9PmwJUaow9h8ybC/lSuwuJdM=";
    });
    date = "2022-09-26";
  };
  "'plugin-gitsigns.nvim'" = {
    pname = "'plugin-gitsigns.nvim'";
    version = "9ff7dfb051e5104088ff80556203634fc8f8546d";
    src = fetchFromGitHub ({
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "9ff7dfb051e5104088ff80556203634fc8f8546d";
      fetchSubmodules = false;
      sha256 = "sha256-u8nHB4QwP1hkfI64MGF5luTof88hTdpF5s1KBr3X2jE=";
    });
    date = "2022-11-09";
  };
  "'plugin-hydra.nvim'" = {
    pname = "'plugin-hydra.nvim'";
    version = "96119af8ebaf0f55567108638c662784d612eb97";
    src = fetchFromGitHub ({
      owner = "anuvyklack";
      repo = "hydra.nvim";
      rev = "96119af8ebaf0f55567108638c662784d612eb97";
      fetchSubmodules = false;
      sha256 = "sha256-ssniRNuDadgfMMKjTzF4wUhfbWdOrrwNGjJUTTgdPX4=";
    });
    date = "2022-11-19";
  };
  "'plugin-impatient.nvim'" = {
    pname = "'plugin-impatient.nvim'";
    version = "d3dd30ff0b811756e735eb9020609fa315bfbbcc";
    src = fetchFromGitHub ({
      owner = "lewis6991";
      repo = "impatient.nvim";
      rev = "d3dd30ff0b811756e735eb9020609fa315bfbbcc";
      fetchSubmodules = false;
      sha256 = "sha256-tsdTHbUC0kYOGonJ1TLIsHnv/RgWGTqHKY3xVj80mxM=";
    });
    date = "2022-11-12";
  };
  "'plugin-keymap-layer.nvim'" = {
    pname = "'plugin-keymap-layer.nvim'";
    version = "e46840f9f377766e856964a49d7f351de3188a38";
    src = fetchFromGitHub ({
      owner = "anuvyklack";
      repo = "keymap-layer.nvim";
      rev = "e46840f9f377766e856964a49d7f351de3188a38";
      fetchSubmodules = false;
      sha256 = "sha256-IfIjh+FOzfI1AXT7n7zfBHLsPCeQoy6/XxWORULWu64=";
    });
    date = "2022-07-17";
  };
  "'plugin-lspkind.nvim'" = {
    pname = "'plugin-lspkind.nvim'";
    version = "c68b3a003483cf382428a43035079f78474cd11e";
    src = fetchFromGitHub ({
      owner = "onsails";
      repo = "lspkind.nvim";
      rev = "c68b3a003483cf382428a43035079f78474cd11e";
      fetchSubmodules = false;
      sha256 = "sha256-WwUQ+O2rIfD4yl0GFx70GsZc9nnhS7b2KWfNdaXCLmM=";
    });
    date = "2022-09-22";
  };
  "'plugin-lualine.nvim'" = {
    pname = "'plugin-lualine.nvim'";
    version = "3325d5d43a7a2bc9baeef2b7e58e1d915278beaf";
    src = fetchFromGitHub ({
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "3325d5d43a7a2bc9baeef2b7e58e1d915278beaf";
      fetchSubmodules = false;
      sha256 = "sha256-pjpxV59Ej7tCvReP5nFi/h1veGwzLdw3PILC89+f488=";
    });
    date = "2022-10-23";
  };
  "'plugin-noice.nvim'" = {
    pname = "'plugin-noice.nvim'";
    version = "b10bbbb91215d0324d7d7f4cd0d8de3d1332648f";
    src = fetchFromGitHub ({
      owner = "folke";
      repo = "noice.nvim";
      rev = "b10bbbb91215d0324d7d7f4cd0d8de3d1332648f";
      fetchSubmodules = false;
      sha256 = "sha256-llhCBLJGV/y1ZYgEvZNq2+kIrTTJasIf8uj57uThqPk=";
    });
    date = "2022-11-17";
  };
  "'plugin-nui.nvim'" = {
    pname = "'plugin-nui.nvim'";
    version = "d12a6977846b2fa978bff89b439e509320854e10";
    src = fetchFromGitHub ({
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "d12a6977846b2fa978bff89b439e509320854e10";
      fetchSubmodules = false;
      sha256 = "sha256-Xs7QSwxPgxxwoqmWvGVqSPlr5IZPm5oaFHBqseVEEr4=";
    });
    date = "2022-10-27";
  };
  "'plugin-null-ls.nvim'" = {
    pname = "'plugin-null-ls.nvim'";
    version = "07d4ed4c6b561914aafd787453a685598bec510f";
    src = fetchFromGitHub ({
      owner = "jose-elias-alvarez";
      repo = "null-ls.nvim";
      rev = "07d4ed4c6b561914aafd787453a685598bec510f";
      fetchSubmodules = false;
      sha256 = "sha256-yo43otYojyGRRNqpYotdheNNbcnSreNEdqZ5irTnbqs=";
    });
    date = "2022-11-10";
  };
  "'plugin-nvim'" = {
    pname = "'plugin-nvim'";
    version = "8d4b9ed1f9cb5a575a1fa25c506409416d347241";
    src = fetchFromGitHub ({
      owner = "catppuccin";
      repo = "nvim";
      rev = "8d4b9ed1f9cb5a575a1fa25c506409416d347241";
      fetchSubmodules = false;
      sha256 = "sha256-VRk+BF6982UuKlqVhiNR85l1s8mDG5oasIYFKNKsRmA=";
    });
    date = "2022-11-19";
  };
  "'plugin-nvim-autopairs'" = {
    pname = "'plugin-nvim-autopairs'";
    version = "6b6e35fc9aca1030a74cc022220bc22ea6c5daf4";
    src = fetchFromGitHub ({
      owner = "windwp";
      repo = "nvim-autopairs";
      rev = "6b6e35fc9aca1030a74cc022220bc22ea6c5daf4";
      fetchSubmodules = false;
      sha256 = "sha256-O9QRLKr6I2csBxKE6fyvkcA7Vgs7PjaQSC4bB7yaWtE=";
    });
    date = "2022-10-27";
  };
  "'plugin-nvim-cmp'" = {
    pname = "'plugin-nvim-cmp'";
    version = "8a9e8a89eec87f86b6245d77f313a040a94081c1";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "nvim-cmp";
      rev = "8a9e8a89eec87f86b6245d77f313a040a94081c1";
      fetchSubmodules = false;
      sha256 = "sha256-Xa/ONH/MO3m1lLA0Oaz9t+GPHhRPTHgL7X93A+gddb4=";
    });
    date = "2022-11-18";
  };
  "'plugin-nvim-colorizer.lua'" = {
    pname = "'plugin-nvim-colorizer.lua'";
    version = "760e27df4dd966607e8fb7fd8b6b93e3c7d2e193";
    src = fetchFromGitHub ({
      owner = "NvChad";
      repo = "nvim-colorizer.lua";
      rev = "760e27df4dd966607e8fb7fd8b6b93e3c7d2e193";
      fetchSubmodules = false;
      sha256 = "sha256-toNEfgZn2RNwyjI5FOyRU9Bdu6jFDZbSb1SjiY9sHH8=";
    });
    date = "2022-10-29";
  };
  "'plugin-nvim-lspconfig'" = {
    pname = "'plugin-nvim-lspconfig'";
    version = "0fd98b0d01bfc5603e56a959acb8e875e4039ac7";
    src = fetchFromGitHub ({
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "0fd98b0d01bfc5603e56a959acb8e875e4039ac7";
      fetchSubmodules = false;
      sha256 = "sha256-BJgfRZMdhiZaX/avRZg9Ppd7N6VoOpqOS/XM4uqwM3Y=";
    });
    date = "2022-11-19";
  };
  "'plugin-nvim-navic'" = {
    pname = "'plugin-nvim-navic'";
    version = "40c0ab2640a0e17c4fad7e17f260414d18852ce6";
    src = fetchFromGitHub ({
      owner = "SmiteshP";
      repo = "nvim-navic";
      rev = "40c0ab2640a0e17c4fad7e17f260414d18852ce6";
      fetchSubmodules = false;
      sha256 = "sha256-SCeDNVP8eYnhNcwShIs2IZI80cXAoIiWLHBLatFFmaQ=";
    });
    date = "2022-11-18";
  };
  "'plugin-nvim-surround'" = {
    pname = "'plugin-nvim-surround'";
    version = "1d83fecd27c6b4b66cc529930552d205fbecb660";
    src = fetchFromGitHub ({
      owner = "kylechui";
      repo = "nvim-surround";
      rev = "1d83fecd27c6b4b66cc529930552d205fbecb660";
      fetchSubmodules = false;
      sha256 = "sha256-awez4H15VnGmmQtiDVwmu8A/falPF7nXzcXVUPvBHaI=";
    });
    date = "2022-11-16";
  };
  "'plugin-nvim-treesitter'" = {
    pname = "'plugin-nvim-treesitter'";
    version = "da90af1a910234078d60795e8f8bb0735c1a15f5";
    src = fetchFromGitHub ({
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "da90af1a910234078d60795e8f8bb0735c1a15f5";
      fetchSubmodules = false;
      sha256 = "sha256-BKfZjq3yJm2JFX8cLVQvVF8GVH0NORCvURY+vP6/GBE=";
    });
    date = "2022-11-19";
  };
  "'plugin-nvim-ts-autotag'" = {
    pname = "'plugin-nvim-ts-autotag'";
    version = "fdefe46c6807441460f11f11a167a2baf8e4534b";
    src = fetchFromGitHub ({
      owner = "windwp";
      repo = "nvim-ts-autotag";
      rev = "fdefe46c6807441460f11f11a167a2baf8e4534b";
      fetchSubmodules = false;
      sha256 = "sha256-ltGiYNXWpWSI5RrWTVR+k6SZjcZbsHtH5m9uHTMKnzM=";
    });
    date = "2022-08-11";
  };
  "'plugin-nvim-ts-context-commentstring'" = {
    pname = "'plugin-nvim-ts-context-commentstring'";
    version = "32d9627123321db65a4f158b72b757bcaef1a3f4";
    src = fetchFromGitHub ({
      owner = "JoosepAlviste";
      repo = "nvim-ts-context-commentstring";
      rev = "32d9627123321db65a4f158b72b757bcaef1a3f4";
      fetchSubmodules = false;
      sha256 = "sha256-l7T8D+JSwvdmrnX9LNJJMtsDeZwU2gG7k5q1PoHFzZw=";
    });
    date = "2022-10-29";
  };
  "'plugin-nvim-ts-rainbow'" = {
    pname = "'plugin-nvim-ts-rainbow'";
    version = "064fd6c0a15fae7f876c2c6dd4524ca3fad96750";
    src = fetchFromGitHub ({
      owner = "p00f";
      repo = "nvim-ts-rainbow";
      rev = "064fd6c0a15fae7f876c2c6dd4524ca3fad96750";
      fetchSubmodules = false;
      sha256 = "sha256-71/dbTPL3zB3oZaHTMvPWmcsr7cyctymzGnRG31H/6w=";
    });
    date = "2022-11-04";
  };
  "'plugin-nvim-ufo'" = {
    pname = "'plugin-nvim-ufo'";
    version = "a346e88c776a7089291c883705c5cd8a6ce67558";
    src = fetchFromGitHub ({
      owner = "kevinhwang91";
      repo = "nvim-ufo";
      rev = "a346e88c776a7089291c883705c5cd8a6ce67558";
      fetchSubmodules = false;
      sha256 = "sha256-OThSxKXD8YqY9SxqYOrG3hHYcMHL6copyfuUj6HxjZw=";
    });
    date = "2022-11-19";
  };
  "'plugin-nvim-web-devicons'" = {
    pname = "'plugin-nvim-web-devicons'";
    version = "3b1b794bc17b7ac3df3ae471f1c18f18d1a0f958";
    src = fetchFromGitHub ({
      owner = "kyazdani42";
      repo = "nvim-web-devicons";
      rev = "3b1b794bc17b7ac3df3ae471f1c18f18d1a0f958";
      fetchSubmodules = false;
      sha256 = "sha256-hxujmUwNtDAXd6JCxBpvPpOzEENQSOYepS7fwmbZufs=";
    });
    date = "2022-11-15";
  };
  "'plugin-octo.nvim'" = {
    pname = "'plugin-octo.nvim'";
    version = "b75630f93822a569f3fc2360bb2066ec1b205bd0";
    src = fetchFromGitHub ({
      owner = "pwntester";
      repo = "octo.nvim";
      rev = "b75630f93822a569f3fc2360bb2066ec1b205bd0";
      fetchSubmodules = false;
      sha256 = "sha256-8UQp6gCsY83HJ6FmEzXjffjSJoFvJs4TIUM/5F9jrfE=";
    });
    date = "2022-10-18";
  };
  "'plugin-overseer.nvim'" = {
    pname = "'plugin-overseer.nvim'";
    version = "3427960953ae27448a1022aed2f9fef3e1de43ac";
    src = fetchFromGitHub ({
      owner = "stevearc";
      repo = "overseer.nvim";
      rev = "3427960953ae27448a1022aed2f9fef3e1de43ac";
      fetchSubmodules = false;
      sha256 = "sha256-NOR0kH1zNOTw4PvbyeDnhQyzd1jsDOryRH3hPMq3hHk=";
    });
    date = "2022-11-18";
  };
  "'plugin-packer.nvim'" = {
    pname = "'plugin-packer.nvim'";
    version = "6afb67460283f0e990d35d229fd38fdc04063e0a";
    src = fetchFromGitHub ({
      owner = "wbthomason";
      repo = "packer.nvim";
      rev = "6afb67460283f0e990d35d229fd38fdc04063e0a";
      fetchSubmodules = false;
      sha256 = "sha256-CiDvG7OFg6T/e0xPm7u1rCSnnPwSLATYtjhEw0jlp/M=";
    });
    date = "2022-09-10";
  };
  "'plugin-playground'" = {
    pname = "'plugin-playground'";
    version = "1290fdf6f2f0189eb3b4ce8073d3fda6a3658376";
    src = fetchFromGitHub ({
      owner = "nvim-treesitter";
      repo = "playground";
      rev = "1290fdf6f2f0189eb3b4ce8073d3fda6a3658376";
      fetchSubmodules = false;
      sha256 = "sha256-oQR0aW/4sUWIA9nBWPOJtZ/T1nQS4MQAX2SJoQqr9vs=";
    });
    date = "2022-11-17";
  };
  "'plugin-plenary.nvim'" = {
    pname = "'plugin-plenary.nvim'";
    version = "4b7e52044bbb84242158d977a50c4cbcd85070c7";
    src = fetchFromGitHub ({
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "4b7e52044bbb84242158d977a50c4cbcd85070c7";
      fetchSubmodules = false;
      sha256 = "sha256-lIdBrVpi+vUudeotjFAuw4C0VT8TPoFE9cVVAQEsAYU=";
    });
    date = "2022-10-01";
  };
  "'plugin-promise-async'" = {
    pname = "'plugin-promise-async'";
    version = "70b09063cdf029079b25c7925e4494e7416ee995";
    src = fetchFromGitHub ({
      owner = "kevinhwang91";
      repo = "promise-async";
      rev = "70b09063cdf029079b25c7925e4494e7416ee995";
      fetchSubmodules = false;
      sha256 = "sha256-rGbi5nCCz1qO6CzoWxbze8iKWP6baqIZBd/Je2LU6jw=";
    });
    date = "2022-09-20";
  };
  "'plugin-silicon.lua'" = {
    pname = "'plugin-silicon.lua'";
    version = "f79c5a326f2f6d641662986b54f0db812ef0369c";
    src = fetchFromGitHub ({
      owner = "narutoxy";
      repo = "silicon.lua";
      rev = "f79c5a326f2f6d641662986b54f0db812ef0369c";
      fetchSubmodules = false;
      sha256 = "sha256-jDjg1H91qj/a/mTv5UuZi27W5fibJEiYVovD+0qi83w=";
    });
    date = "2022-11-16";
  };
  "'plugin-splitjoin.vim'" = {
    pname = "'plugin-splitjoin.vim'";
    version = "956d67c88512b91c2938da3a9e0aeeea2b82cd0b";
    src = fetchFromGitHub ({
      owner = "AndrewRadev";
      repo = "splitjoin.vim";
      rev = "956d67c88512b91c2938da3a9e0aeeea2b82cd0b";
      fetchSubmodules = false;
      sha256 = "sha256-frMb0OXp0e+cg5mtEjAzO//iMnajTOBUiNrR3viuAUA=";
    });
    date = "2022-09-04";
  };
  "'plugin-targets.vim'" = {
    pname = "'plugin-targets.vim'";
    version = "8d6ff2984cdfaebe5b7a6eee8f226a6dd1226f2d";
    src = fetchFromGitHub ({
      owner = "wellle";
      repo = "targets.vim";
      rev = "8d6ff2984cdfaebe5b7a6eee8f226a6dd1226f2d";
      fetchSubmodules = false;
      sha256 = "sha256-Sd+2dppKHpa7ONK6JgCAFKwjDMueaChFtSF0YvrAXKQ=";
    });
    date = "2019-12-08";
  };
  "'plugin-telescope-fzf-native.nvim'" = {
    pname = "'plugin-telescope-fzf-native.nvim'";
    version = "65c0ee3d4bb9cb696e262bca1ea5e9af3938fc90";
    src = fetchFromGitHub ({
      owner = "nvim-telescope";
      repo = "telescope-fzf-native.nvim";
      rev = "65c0ee3d4bb9cb696e262bca1ea5e9af3938fc90";
      fetchSubmodules = false;
      sha256 = "sha256-hdQuS7AcvN5vIXBJnSwFsuyvX89+XDrSsea9TBWF21s=";
    });
    date = "2022-09-06";
  };
  "'plugin-telescope-live-grep-args.nvim'" = {
    pname = "'plugin-telescope-live-grep-args.nvim'";
    version = "7de3baef1ec4fb77f7a8195fe87bebd513244b6a";
    src = fetchFromGitHub ({
      owner = "nvim-telescope";
      repo = "telescope-live-grep-args.nvim";
      rev = "7de3baef1ec4fb77f7a8195fe87bebd513244b6a";
      fetchSubmodules = false;
      sha256 = "sha256-RgGCaAolEWMXJet547ce0oW0+zsxQzXrKn+O9WgV1nk=";
    });
    date = "2022-11-07";
  };
  "'plugin-telescope.nvim'" = {
    pname = "'plugin-telescope.nvim'";
    version = "7a4ffef931769c3fe7544214ed7ffde5852653f6";
    src = fetchFromGitHub ({
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "7a4ffef931769c3fe7544214ed7ffde5852653f6";
      fetchSubmodules = false;
      sha256 = "sha256-U5H4bpQ087pCS/HoHNgrbsH9wARdccDpXLxY++75TFg=";
    });
    date = "2022-11-11";
  };
  "'plugin-todo-comments.nvim'" = {
    pname = "'plugin-todo-comments.nvim'";
    version = "1b9df577262b2c4c4ea422161742927f80ffa131";
    src = fetchFromGitHub ({
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "1b9df577262b2c4c4ea422161742927f80ffa131";
      fetchSubmodules = false;
      sha256 = "sha256-8RP0vtz0wj9d2rz4WY+cTOCui9k56Hsa8glBXPaK0ZM=";
    });
    date = "2022-11-16";
  };
  "'plugin-trouble.nvim'" = {
    pname = "'plugin-trouble.nvim'";
    version = "897542f90050c3230856bc6e45de58b94c700bbf";
    src = fetchFromGitHub ({
      owner = "folke";
      repo = "trouble.nvim";
      rev = "897542f90050c3230856bc6e45de58b94c700bbf";
      fetchSubmodules = false;
      sha256 = "sha256-8IJB4cIT85GkManiRSelGEMGudnGwZ5Vr+CJwTv40SY=";
    });
    date = "2022-11-16";
  };
  "'plugin-vim-wordmotion'" = {
    pname = "'plugin-vim-wordmotion'";
    version = "5dd613ed68a0ecf0fc6c11cd4098c03583786bf0";
    src = fetchFromGitHub ({
      owner = "chaoren";
      repo = "vim-wordmotion";
      rev = "5dd613ed68a0ecf0fc6c11cd4098c03583786bf0";
      fetchSubmodules = false;
      sha256 = "sha256-0Rzd+td/8S9vR/AJU058HX2auBAm+rNNAKAm2ribPl0=";
    });
    date = "2022-07-04";
  };
  "'plugin-zk-nvim'" = {
    pname = "'plugin-zk-nvim'";
    version = "1d2ebc679eeea8bfddc908e31bbe9e8b0928ef21";
    src = fetchFromGitHub ({
      owner = "mickael-menu";
      repo = "zk-nvim";
      rev = "1d2ebc679eeea8bfddc908e31bbe9e8b0928ef21";
      fetchSubmodules = false;
      sha256 = "sha256-S2RqOPT1CIXgH40AQ6rZsV1AbUGH3uA2R8chq4dXy0Y=";
    });
    date = "2022-11-13";
  };
}
