# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  "'plugin-Comment.nvim'" = {
    pname = "'plugin-Comment.nvim'";
    version = "ad7ffa8ed2279f1c8a90212c7d3851f9b783a3d6";
    src = fetchFromGitHub ({
      owner = "numToStr";
      repo = "Comment.nvim";
      rev = "ad7ffa8ed2279f1c8a90212c7d3851f9b783a3d6";
      fetchSubmodules = false;
      sha256 = "sha256-YJf4RKX/HZ8DfpyTqNXDk1hh7iCpGUmvhT+8VJViwr8=";
    });
    date = "2022-10-14";
  };
  "'plugin-LuaSnip'" = {
    pname = "'plugin-LuaSnip'";
    version = "619796e2477f7233e5fdff456240676a08482684";
    src = fetchFromGitHub ({
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "619796e2477f7233e5fdff456240676a08482684";
      fetchSubmodules = false;
      sha256 = "sha256-sBaoVQJ/thUu8A+b0jw7kk0dwul4BqPiDpI3xYFHmWg=";
    });
    date = "2022-11-01";
  };
  "'plugin-SchemaStore.nvim'" = {
    pname = "'plugin-SchemaStore.nvim'";
    version = "bfcd9a05ded8ff6cf89b302bee548c35177d9158";
    src = fetchFromGitHub ({
      owner = "b0o";
      repo = "SchemaStore.nvim";
      rev = "bfcd9a05ded8ff6cf89b302bee548c35177d9158";
      fetchSubmodules = false;
      sha256 = "sha256-lfReA+bI9cImoJUYdvXLg3t4UCSg4GXMmf7yM2Ezktc=";
    });
    date = "2022-10-31";
  };
  "'plugin-bufdelete.nvim'" = {
    pname = "'plugin-bufdelete.nvim'";
    version = "e88dbe0ba5829119d8edb5fc69d3c8553e324a93";
    src = fetchFromGitHub ({
      owner = "famiu";
      repo = "bufdelete.nvim";
      rev = "e88dbe0ba5829119d8edb5fc69d3c8553e324a93";
      fetchSubmodules = false;
      sha256 = "sha256-Zu1G3nt14vnEzjsy55IZAGCHHqPOQLZw2YcA1LcsSmI=";
    });
    date = "2022-10-07";
  };
  "'plugin-cmp-cmdline'" = {
    pname = "'plugin-cmp-cmdline'";
    version = "c66c379915d68fb52ad5ad1195cdd4265a95ef1e";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-cmdline";
      rev = "c66c379915d68fb52ad5ad1195cdd4265a95ef1e";
      fetchSubmodules = false;
      sha256 = "sha256-IvMI9wHN1llFLpgMGwm6yr60UJ6gaWBnZaxNHXCDOwI=";
    });
    date = "2022-09-16";
  };
  "'plugin-cmp-git'" = {
    pname = "'plugin-cmp-git'";
    version = "169202582f900b0e189eed5153b291383bfbba47";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-git";
      rev = "169202582f900b0e189eed5153b291383bfbba47";
      fetchSubmodules = false;
      sha256 = "sha256-1UjjqMBq3+B/TKVdYH4N3a0MZLs4LKoLsdAF0gyP0TY=";
    });
    date = "2021-10-29";
  };
  "'plugin-cmp-nvim-lsp'" = {
    pname = "'plugin-cmp-nvim-lsp'";
    version = "78924d1d677b29b3d1fe429864185341724ee5a2";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-nvim-lsp";
      rev = "78924d1d677b29b3d1fe429864185341724ee5a2";
      fetchSubmodules = false;
      sha256 = "sha256-amY87Q2HQseMoEFJW8YFf6k5UUWru52498EoDs4m9r8=";
    });
    date = "2022-10-29";
  };
  "'plugin-cmp-path'" = {
    pname = "'plugin-cmp-path'";
    version = "91ff86cd9c29299a64f968ebb45846c485725f23";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-path";
      rev = "91ff86cd9c29299a64f968ebb45846c485725f23";
      fetchSubmodules = false;
      sha256 = "sha256-thppiiV3wjIaZnAXmsh7j3DUc6ceSCvGzviwFUnoPaI=";
    });
    date = "2022-10-03";
  };
  "'plugin-cmp_luasnip'" = {
    pname = "'plugin-cmp_luasnip'";
    version = "18095520391186d634a0045dacaa346291096566";
    src = fetchFromGitHub ({
      owner = "saadparwaiz1";
      repo = "cmp_luasnip";
      rev = "18095520391186d634a0045dacaa346291096566";
      fetchSubmodules = false;
      sha256 = "sha256-Z5SPy3j2oHFxJ7bK8DP8Q/oRyLEMlnWyIfDaQcNVIS0=";
    });
    date = "2022-10-28";
  };
  "'plugin-colorful-winsep.nvim'" = {
    pname = "'plugin-colorful-winsep.nvim'";
    version = "23b0b419980206fa1d45034dfd88d60c9344250a";
    src = fetchFromGitHub ({
      owner = "nvim-zh";
      repo = "colorful-winsep.nvim";
      rev = "23b0b419980206fa1d45034dfd88d60c9344250a";
      fetchSubmodules = false;
      sha256 = "sha256-B3RIYLX3u77EzhlLIQ/xt0kL37j/YQyT36mguxQCjy8=";
    });
    date = "2022-11-01";
  };
  "'plugin-diffview.nvim'" = {
    pname = "'plugin-diffview.nvim'";
    version = "94a3422415a092db1f2e00af5bd7db4ec1c6b8d7";
    src = fetchFromGitHub ({
      owner = "sindrets";
      repo = "diffview.nvim";
      rev = "94a3422415a092db1f2e00af5bd7db4ec1c6b8d7";
      fetchSubmodules = false;
      sha256 = "sha256-d0AfrZkS6XUw/q6VruLdO/uGQ74XD6jRv1V+x2EbjwU=";
    });
    date = "2022-10-26";
  };
  "'plugin-dressing.nvim'" = {
    pname = "'plugin-dressing.nvim'";
    version = "12b808a6867e8c38015488ad6cee4e3d58174182";
    src = fetchFromGitHub ({
      owner = "stevearc";
      repo = "dressing.nvim";
      rev = "12b808a6867e8c38015488ad6cee4e3d58174182";
      fetchSubmodules = false;
      sha256 = "sha256-qn84Ny9JsWRMFMYu/sir2RwlCk6IP+GSr7Zxn/Du+gw=";
    });
    date = "2022-10-03";
  };
  "'plugin-editorconfig.nvim'" = {
    pname = "'plugin-editorconfig.nvim'";
    version = "e72d2331b43e3f08d0ecca44cecded4e20c01fab";
    src = fetchFromGitHub ({
      owner = "gpanders";
      repo = "editorconfig.nvim";
      rev = "e72d2331b43e3f08d0ecca44cecded4e20c01fab";
      fetchSubmodules = false;
      sha256 = "sha256-Ylk1KdJtXHwR2ekEvIQSwHaAfxnMB2nL7Tw7EJZ56gw=";
    });
    date = "2022-11-01";
  };
  "'plugin-fm-nvim'" = {
    pname = "'plugin-fm-nvim'";
    version = "8e6a77049330e7c797eb9e63affd75eb796fe75e";
    src = fetchFromGitHub ({
      owner = "is0n";
      repo = "fm-nvim";
      rev = "8e6a77049330e7c797eb9e63affd75eb796fe75e";
      fetchSubmodules = false;
      sha256 = "sha256-I29p08P4Wh/LLTDZIQ2TkYy5Kdj0G8loU6k3eFM+iVE=";
    });
    date = "2022-10-10";
  };
  "'plugin-git-worktree.nvim'" = {
    pname = "'plugin-git-worktree.nvim'";
    version = "d7f4e2584e81670154f07ca9fa5dd791d9c1b458";
    src = fetchFromGitHub ({
      owner = "ThePrimeagen";
      repo = "git-worktree.nvim";
      rev = "d7f4e2584e81670154f07ca9fa5dd791d9c1b458";
      fetchSubmodules = false;
      sha256 = "sha256-pkJkdt2XC1w0s1VpnxJFnoYiEgD01MZ7a5i2AlU1hMw=";
    });
    date = "2021-12-24";
  };
  "'plugin-gitlinker.nvim'" = {
    pname = "'plugin-gitlinker.nvim'";
    version = "c68d4873a14d2ae614875685ccca2e49472989e8";
    src = fetchFromGitHub ({
      owner = "ruifm";
      repo = "gitlinker.nvim";
      rev = "c68d4873a14d2ae614875685ccca2e49472989e8";
      fetchSubmodules = false;
      sha256 = "sha256-yPEKz2iahD1dwXCXeci9PmwJUaow9h8ybC/lSuwuJdM=";
    });
    date = "2022-09-26";
  };
  "'plugin-gitsigns.nvim'" = {
    pname = "'plugin-gitsigns.nvim'";
    version = "d3a8ba0b0d34bbac482b963e52b346065169fa20";
    src = fetchFromGitHub ({
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "d3a8ba0b0d34bbac482b963e52b346065169fa20";
      fetchSubmodules = false;
      sha256 = "sha256-dpCw1JsYfr+dwxRUrqBJvq8nAARI3m5MHIbMRN/3j2w=";
    });
    date = "2022-10-31";
  };
  "'plugin-hydra.nvim'" = {
    pname = "'plugin-hydra.nvim'";
    version = "fa41a971765d4cce9c39185289f5a10894f66dbd";
    src = fetchFromGitHub ({
      owner = "anuvyklack";
      repo = "hydra.nvim";
      rev = "fa41a971765d4cce9c39185289f5a10894f66dbd";
      fetchSubmodules = false;
      sha256 = "sha256-4X9TAi/bH7JIKRuRYONcYVtSsmyz912V5KOI4QefC6U=";
    });
    date = "2022-10-02";
  };
  "'plugin-impatient.nvim'" = {
    pname = "'plugin-impatient.nvim'";
    version = "b842e16ecc1a700f62adb9802f8355b99b52a5a6";
    src = fetchFromGitHub ({
      owner = "lewis6991";
      repo = "impatient.nvim";
      rev = "b842e16ecc1a700f62adb9802f8355b99b52a5a6";
      fetchSubmodules = false;
      sha256 = "sha256-zUsj9JtyG1gNZ276mIs6uZtTWN9LRYiRlnZQlOyonuA=";
    });
    date = "2022-08-19";
  };
  "'plugin-keymap-layer.nvim'" = {
    pname = "'plugin-keymap-layer.nvim'";
    version = "e46840f9f377766e856964a49d7f351de3188a38";
    src = fetchFromGitHub ({
      owner = "anuvyklack";
      repo = "keymap-layer.nvim";
      rev = "e46840f9f377766e856964a49d7f351de3188a38";
      fetchSubmodules = false;
      sha256 = "sha256-IfIjh+FOzfI1AXT7n7zfBHLsPCeQoy6/XxWORULWu64=";
    });
    date = "2022-07-17";
  };
  "'plugin-lspkind.nvim'" = {
    pname = "'plugin-lspkind.nvim'";
    version = "c68b3a003483cf382428a43035079f78474cd11e";
    src = fetchFromGitHub ({
      owner = "onsails";
      repo = "lspkind.nvim";
      rev = "c68b3a003483cf382428a43035079f78474cd11e";
      fetchSubmodules = false;
      sha256 = "sha256-WwUQ+O2rIfD4yl0GFx70GsZc9nnhS7b2KWfNdaXCLmM=";
    });
    date = "2022-09-22";
  };
  "'plugin-lualine.nvim'" = {
    pname = "'plugin-lualine.nvim'";
    version = "3325d5d43a7a2bc9baeef2b7e58e1d915278beaf";
    src = fetchFromGitHub ({
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "3325d5d43a7a2bc9baeef2b7e58e1d915278beaf";
      fetchSubmodules = false;
      sha256 = "sha256-pjpxV59Ej7tCvReP5nFi/h1veGwzLdw3PILC89+f488=";
    });
    date = "2022-10-23";
  };
  "'plugin-noice.nvim'" = {
    pname = "'plugin-noice.nvim'";
    version = "7b62ccfc236e51e78e5b2fc7d3068eacd65e4590";
    src = fetchFromGitHub ({
      owner = "folke";
      repo = "noice.nvim";
      rev = "7b62ccfc236e51e78e5b2fc7d3068eacd65e4590";
      fetchSubmodules = false;
      sha256 = "sha256-YLvsu1A0pjIXA7Fq/MVwot5eykZbrdaKh85szVAEXpQ=";
    });
    date = "2022-10-29";
  };
  "'plugin-nui.nvim'" = {
    pname = "'plugin-nui.nvim'";
    version = "d12a6977846b2fa978bff89b439e509320854e10";
    src = fetchFromGitHub ({
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "d12a6977846b2fa978bff89b439e509320854e10";
      fetchSubmodules = false;
      sha256 = "sha256-Xs7QSwxPgxxwoqmWvGVqSPlr5IZPm5oaFHBqseVEEr4=";
    });
    date = "2022-10-27";
  };
  "'plugin-null-ls.nvim'" = {
    pname = "'plugin-null-ls.nvim'";
    version = "f1add2302e6a01531a007c51054392d2029dbed4";
    src = fetchFromGitHub ({
      owner = "jose-elias-alvarez";
      repo = "null-ls.nvim";
      rev = "f1add2302e6a01531a007c51054392d2029dbed4";
      fetchSubmodules = false;
      sha256 = "sha256-zzOTWXW9HlzGbX8OnvrimuY1EiUAM5Il1Loi0UPpFBQ=";
    });
    date = "2022-10-26";
  };
  "'plugin-nvim'" = {
    pname = "'plugin-nvim'";
    version = "c4f0f1a88304378cb76ac0a0c00a99f6d58f972f";
    src = fetchFromGitHub ({
      owner = "catppuccin";
      repo = "nvim";
      rev = "c4f0f1a88304378cb76ac0a0c00a99f6d58f972f";
      fetchSubmodules = false;
      sha256 = "sha256-75dcQSY61psLq/6qRFM4PKFqy+NLlwQRm7srVR7EY1U=";
    });
    date = "2022-10-31";
  };
  "'plugin-nvim-autopairs'" = {
    pname = "'plugin-nvim-autopairs'";
    version = "6b6e35fc9aca1030a74cc022220bc22ea6c5daf4";
    src = fetchFromGitHub ({
      owner = "windwp";
      repo = "nvim-autopairs";
      rev = "6b6e35fc9aca1030a74cc022220bc22ea6c5daf4";
      fetchSubmodules = false;
      sha256 = "sha256-O9QRLKr6I2csBxKE6fyvkcA7Vgs7PjaQSC4bB7yaWtE=";
    });
    date = "2022-10-27";
  };
  "'plugin-nvim-cmp'" = {
    pname = "'plugin-nvim-cmp'";
    version = "9bb8ee6e2d6ab3c8cc53323b79f05886bc722faa";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "nvim-cmp";
      rev = "9bb8ee6e2d6ab3c8cc53323b79f05886bc722faa";
      fetchSubmodules = false;
      sha256 = "sha256-FqCrXjjMbYd8D7BdvixQeMGCL1FF551LEfBW1f0o6/w=";
    });
    date = "2022-10-29";
  };
  "'plugin-nvim-colorizer.lua'" = {
    pname = "'plugin-nvim-colorizer.lua'";
    version = "760e27df4dd966607e8fb7fd8b6b93e3c7d2e193";
    src = fetchFromGitHub ({
      owner = "NvChad";
      repo = "nvim-colorizer.lua";
      rev = "760e27df4dd966607e8fb7fd8b6b93e3c7d2e193";
      fetchSubmodules = false;
      sha256 = "sha256-toNEfgZn2RNwyjI5FOyRU9Bdu6jFDZbSb1SjiY9sHH8=";
    });
    date = "2022-10-29";
  };
  "'plugin-nvim-lspconfig'" = {
    pname = "'plugin-nvim-lspconfig'";
    version = "5f4b1fa83c80f43e434c1fb227967dac9ad8f44c";
    src = fetchFromGitHub ({
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "5f4b1fa83c80f43e434c1fb227967dac9ad8f44c";
      fetchSubmodules = false;
      sha256 = "sha256-qLESFhjOoj948fb3Cf+0zw5R/PdQmMokBU8G1+Qxbq8=";
    });
    date = "2022-11-01";
  };
  "'plugin-nvim-navic'" = {
    pname = "'plugin-nvim-navic'";
    version = "2fad33454cd6e37527a2d41f310d77b552d8c1e0";
    src = fetchFromGitHub ({
      owner = "SmiteshP";
      repo = "nvim-navic";
      rev = "2fad33454cd6e37527a2d41f310d77b552d8c1e0";
      fetchSubmodules = false;
      sha256 = "sha256-NwYmcnqGh4YlPL8e+XdPNP5vdw0RO//SUn5yhb+yrP0=";
    });
    date = "2022-11-02";
  };
  "'plugin-nvim-surround'" = {
    pname = "'plugin-nvim-surround'";
    version = "7e5096b736ae252d04d543af6a13280125dc6d0f";
    src = fetchFromGitHub ({
      owner = "kylechui";
      repo = "nvim-surround";
      rev = "7e5096b736ae252d04d543af6a13280125dc6d0f";
      fetchSubmodules = false;
      sha256 = "sha256-EcygUu05HRYPbF71CIgrxitphFSkxdv+oP5ItwBDCsM=";
    });
    date = "2022-10-28";
  };
  "'plugin-nvim-treesitter'" = {
    pname = "'plugin-nvim-treesitter'";
    version = "c6992f69d303cee0b43fd59125cb7afb0262d8fe";
    src = fetchFromGitHub ({
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "c6992f69d303cee0b43fd59125cb7afb0262d8fe";
      fetchSubmodules = false;
      sha256 = "sha256-OMTi1rwnCbDotl+izfs6vwbaERlZjwBOMzSWgqJCB+c=";
    });
    date = "2022-11-01";
  };
  "'plugin-nvim-ts-autotag'" = {
    pname = "'plugin-nvim-ts-autotag'";
    version = "fdefe46c6807441460f11f11a167a2baf8e4534b";
    src = fetchFromGitHub ({
      owner = "windwp";
      repo = "nvim-ts-autotag";
      rev = "fdefe46c6807441460f11f11a167a2baf8e4534b";
      fetchSubmodules = false;
      sha256 = "sha256-ltGiYNXWpWSI5RrWTVR+k6SZjcZbsHtH5m9uHTMKnzM=";
    });
    date = "2022-08-11";
  };
  "'plugin-nvim-ts-context-commentstring'" = {
    pname = "'plugin-nvim-ts-context-commentstring'";
    version = "32d9627123321db65a4f158b72b757bcaef1a3f4";
    src = fetchFromGitHub ({
      owner = "JoosepAlviste";
      repo = "nvim-ts-context-commentstring";
      rev = "32d9627123321db65a4f158b72b757bcaef1a3f4";
      fetchSubmodules = false;
      sha256 = "sha256-l7T8D+JSwvdmrnX9LNJJMtsDeZwU2gG7k5q1PoHFzZw=";
    });
    date = "2022-10-29";
  };
  "'plugin-nvim-ts-rainbow'" = {
    pname = "'plugin-nvim-ts-rainbow'";
    version = "1ec3f880585c644ddd50a51502c59f4e36f03e62";
    src = fetchFromGitHub ({
      owner = "p00f";
      repo = "nvim-ts-rainbow";
      rev = "1ec3f880585c644ddd50a51502c59f4e36f03e62";
      fetchSubmodules = false;
      sha256 = "sha256-sNCatQu1U5V5dlxRayXacxSfWPUgL6Si0na2XHodgAw=";
    });
    date = "2022-09-30";
  };
  "'plugin-nvim-ufo'" = {
    pname = "'plugin-nvim-ufo'";
    version = "5da70eb121a890df8a5b25e6cc30d88665af97b8";
    src = fetchFromGitHub ({
      owner = "kevinhwang91";
      repo = "nvim-ufo";
      rev = "5da70eb121a890df8a5b25e6cc30d88665af97b8";
      fetchSubmodules = false;
      sha256 = "sha256-cOvy9giC9QrjRn1+MkeXayVdDAFq6XelyvT5s1GUgwg=";
    });
    date = "2022-10-30";
  };
  "'plugin-nvim-web-devicons'" = {
    pname = "'plugin-nvim-web-devicons'";
    version = "9061e2d355ecaa2b588b71a35e7a11358a7e51e1";
    src = fetchFromGitHub ({
      owner = "kyazdani42";
      repo = "nvim-web-devicons";
      rev = "9061e2d355ecaa2b588b71a35e7a11358a7e51e1";
      fetchSubmodules = false;
      sha256 = "sha256-kpg9K8WtZHp5FP+23AQK3W0yQOK1ZB6z8kHvy8jcHxM=";
    });
    date = "2022-10-17";
  };
  "'plugin-octo.nvim'" = {
    pname = "'plugin-octo.nvim'";
    version = "b75630f93822a569f3fc2360bb2066ec1b205bd0";
    src = fetchFromGitHub ({
      owner = "pwntester";
      repo = "octo.nvim";
      rev = "b75630f93822a569f3fc2360bb2066ec1b205bd0";
      fetchSubmodules = false;
      sha256 = "sha256-8UQp6gCsY83HJ6FmEzXjffjSJoFvJs4TIUM/5F9jrfE=";
    });
    date = "2022-10-18";
  };
  "'plugin-overseer.nvim'" = {
    pname = "'plugin-overseer.nvim'";
    version = "a17547aaa61541f9c8623974e18d6933f87396e0";
    src = fetchFromGitHub ({
      owner = "stevearc";
      repo = "overseer.nvim";
      rev = "a17547aaa61541f9c8623974e18d6933f87396e0";
      fetchSubmodules = false;
      sha256 = "sha256-W3bD+RIsNYeovvmgbPW5Y3bmjYxNTyKVzLAFYYPedVA=";
    });
    date = "2022-11-01";
  };
  "'plugin-packer.nvim'" = {
    pname = "'plugin-packer.nvim'";
    version = "6afb67460283f0e990d35d229fd38fdc04063e0a";
    src = fetchFromGitHub ({
      owner = "wbthomason";
      repo = "packer.nvim";
      rev = "6afb67460283f0e990d35d229fd38fdc04063e0a";
      fetchSubmodules = false;
      sha256 = "sha256-CiDvG7OFg6T/e0xPm7u1rCSnnPwSLATYtjhEw0jlp/M=";
    });
    date = "2022-09-10";
  };
  "'plugin-playground'" = {
    pname = "'plugin-playground'";
    version = "e6a0bfaf9b5e36e3a327a1ae9a44a989eae472cf";
    src = fetchFromGitHub ({
      owner = "nvim-treesitter";
      repo = "playground";
      rev = "e6a0bfaf9b5e36e3a327a1ae9a44a989eae472cf";
      fetchSubmodules = false;
      sha256 = "sha256-wst6YwtTJbR65+jijSSgsS9Isv1/vO9uAjuoUg6tVQc=";
    });
    date = "2022-09-19";
  };
  "'plugin-plenary.nvim'" = {
    pname = "'plugin-plenary.nvim'";
    version = "4b7e52044bbb84242158d977a50c4cbcd85070c7";
    src = fetchFromGitHub ({
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "4b7e52044bbb84242158d977a50c4cbcd85070c7";
      fetchSubmodules = false;
      sha256 = "sha256-lIdBrVpi+vUudeotjFAuw4C0VT8TPoFE9cVVAQEsAYU=";
    });
    date = "2022-10-01";
  };
  "'plugin-promise-async'" = {
    pname = "'plugin-promise-async'";
    version = "70b09063cdf029079b25c7925e4494e7416ee995";
    src = fetchFromGitHub ({
      owner = "kevinhwang91";
      repo = "promise-async";
      rev = "70b09063cdf029079b25c7925e4494e7416ee995";
      fetchSubmodules = false;
      sha256 = "sha256-rGbi5nCCz1qO6CzoWxbze8iKWP6baqIZBd/Je2LU6jw=";
    });
    date = "2022-09-20";
  };
  "'plugin-silicon.lua'" = {
    pname = "'plugin-silicon.lua'";
    version = "b17444e25f395fd7c7c712b46aa7977cc8433c84";
    src = fetchFromGitHub ({
      owner = "narutoxy";
      repo = "silicon.lua";
      rev = "b17444e25f395fd7c7c712b46aa7977cc8433c84";
      fetchSubmodules = false;
      sha256 = "sha256-nFcCeXWHO6+YXfuUUXuxgjBHyYaPO0myj0fkeqyxPFA=";
    });
    date = "2022-10-27";
  };
  "'plugin-splitjoin.vim'" = {
    pname = "'plugin-splitjoin.vim'";
    version = "956d67c88512b91c2938da3a9e0aeeea2b82cd0b";
    src = fetchFromGitHub ({
      owner = "AndrewRadev";
      repo = "splitjoin.vim";
      rev = "956d67c88512b91c2938da3a9e0aeeea2b82cd0b";
      fetchSubmodules = false;
      sha256 = "sha256-frMb0OXp0e+cg5mtEjAzO//iMnajTOBUiNrR3viuAUA=";
    });
    date = "2022-09-04";
  };
  "'plugin-targets.vim'" = {
    pname = "'plugin-targets.vim'";
    version = "8d6ff2984cdfaebe5b7a6eee8f226a6dd1226f2d";
    src = fetchFromGitHub ({
      owner = "wellle";
      repo = "targets.vim";
      rev = "8d6ff2984cdfaebe5b7a6eee8f226a6dd1226f2d";
      fetchSubmodules = false;
      sha256 = "sha256-Sd+2dppKHpa7ONK6JgCAFKwjDMueaChFtSF0YvrAXKQ=";
    });
    date = "2019-12-08";
  };
  "'plugin-telescope-fzf-native.nvim'" = {
    pname = "'plugin-telescope-fzf-native.nvim'";
    version = "65c0ee3d4bb9cb696e262bca1ea5e9af3938fc90";
    src = fetchFromGitHub ({
      owner = "nvim-telescope";
      repo = "telescope-fzf-native.nvim";
      rev = "65c0ee3d4bb9cb696e262bca1ea5e9af3938fc90";
      fetchSubmodules = false;
      sha256 = "sha256-hdQuS7AcvN5vIXBJnSwFsuyvX89+XDrSsea9TBWF21s=";
    });
    date = "2022-09-06";
  };
  "'plugin-telescope-live-grep-args.nvim'" = {
    pname = "'plugin-telescope-live-grep-args.nvim'";
    version = "54eaae1a84b51e2774c7b6f948d70dd11d46dee5";
    src = fetchFromGitHub ({
      owner = "nvim-telescope";
      repo = "telescope-live-grep-args.nvim";
      rev = "54eaae1a84b51e2774c7b6f948d70dd11d46dee5";
      fetchSubmodules = false;
      sha256 = "sha256-GAJuPtxbGp+JGHjE4IhqJaZzXB2d25Z28EdW848FSdw=";
    });
    date = "2022-10-27";
  };
  "'plugin-telescope.nvim'" = {
    pname = "'plugin-telescope.nvim'";
    version = "4bd4205028d6588cf2e0a1346687a6039b0f0a7c";
    src = fetchFromGitHub ({
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "4bd4205028d6588cf2e0a1346687a6039b0f0a7c";
      fetchSubmodules = false;
      sha256 = "sha256-S3wcz/4LAlZawp7LvzkQZ+GwCHdCtdd1z/iMqvqTSO8=";
    });
    date = "2022-10-31";
  };
  "'plugin-todo-comments.nvim'" = {
    pname = "'plugin-todo-comments.nvim'";
    version = "530eb3a896e9eef270f00f4baafa102361afc93b";
    src = fetchFromGitHub ({
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "530eb3a896e9eef270f00f4baafa102361afc93b";
      fetchSubmodules = false;
      sha256 = "sha256-8sSPpg6G/EHVCm2bZV5LZHn/+Kxdq47IEum4oWyrYa4=";
    });
    date = "2022-10-28";
  };
  "'plugin-trouble.nvim'" = {
    pname = "'plugin-trouble.nvim'";
    version = "ed65f84abc4a1e5d8f368d7e02601fc0357ea15e";
    src = fetchFromGitHub ({
      owner = "folke";
      repo = "trouble.nvim";
      rev = "ed65f84abc4a1e5d8f368d7e02601fc0357ea15e";
      fetchSubmodules = false;
      sha256 = "sha256-kpOJnyAStqx+R5iMLpHAiW1h8ljjnSAwKgvFi667M1Y=";
    });
    date = "2022-10-14";
  };
  "'plugin-vim-wordmotion'" = {
    pname = "'plugin-vim-wordmotion'";
    version = "5dd613ed68a0ecf0fc6c11cd4098c03583786bf0";
    src = fetchFromGitHub ({
      owner = "chaoren";
      repo = "vim-wordmotion";
      rev = "5dd613ed68a0ecf0fc6c11cd4098c03583786bf0";
      fetchSubmodules = false;
      sha256 = "sha256-0Rzd+td/8S9vR/AJU058HX2auBAm+rNNAKAm2ribPl0=";
    });
    date = "2022-07-04";
  };
  "'plugin-zk-nvim'" = {
    pname = "'plugin-zk-nvim'";
    version = "73affbc95fba3655704e4993a8929675bc9942a1";
    src = fetchFromGitHub ({
      owner = "mickael-menu";
      repo = "zk-nvim";
      rev = "73affbc95fba3655704e4993a8929675bc9942a1";
      fetchSubmodules = false;
      sha256 = "sha256-BQrF88hVSDc9zjCWcSSCnw1yhCfMu8zsMbilAI0Xh2c=";
    });
    date = "2022-07-14";
  };
}
